# Generated by Django 6.0 on 2025-12-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('note', 'Note'), ('paper', 'Previous Paper')], max_length=10)),
                ('price', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
